#!/usr/bin/env python3
import sys
import subprocess
from urllib.parse import urlparse, parse_qs

if __name__ == "__main__":

       subprocess.Popen(["sudo /usr/local/bin/starfish",  github.com/fahad-israr/starfish])
